### PR TITLE
[Workflow] Add basic makefile

### PR DESCRIPTION
**Pull request by MKyhos**
This PR adds a makefile to support basic dev workflows.

Note: the release functionality is not yet ready, will work a bit more on this later.

### CODE REVIEW

**Review by pr130 — APPROVED** [review]
just one small question: 

on dev, the version in `DESCRIPTION` should be something like  `0.0.3000` right? so in order to prepare a release, what would be a good workflow:

a) prepare release on `dev` , then merge to main, and change back version to 0.0.3000 on dev?
b) branch off `dev`, change version number and then merge into `main`? 
c) ...?

What do you think? I'll happily document that workflow in the Wiki :) 

Otherwise, outstanding `make` wörk as always (or should I say `mk` work? ;)) :) 💪 

Ps: is the release functionality ready or not? :D

**Comment by MKyhos** [comment]
Great :) 
The release functionality needs probably some more work, I will it just merge it as is and fix it on the go then?

RE workfow:
Yes I would say:
- increase the package version in DESCRIPTION on `dev`. Also probably, edit some `NEWS.md` 
- squash merge into `main`. Then, on main:
- create tag (equiv to version number)
- create release
- as soon as `dev` is again ahead of `main`, increase version number by some patch number etc

Or did I miss something? :)

**Comment by pr130** [comment]
@MKyhos thanks for the explanation. I put it down here: https://github.com/CorrelAid/kbtbr/wiki/Releasing-kbtbr 
i always get a bit confused with the releases and the tags. is it correct to use the lightweight tags to tag before releasing? or does it even matter that much?

**Comment by MKyhos** [comment]
A tag is needed beforehand, so it is used while creating the Release to refer to a certain version of the code
1. create tag, e.g. 1.2.3
2. create release based on tag 1.2.3 

Im GitHub UI kann man glaube ich aber auch im Release dialog direkt dort den Tag anlegen, wenn es noch keinen passenden gibt

**Pull request merged**
