### PR TITLE
Issue29 manage output get

### PR DESCRIPTION
**Pull request by dimitri-mar**
Get function in the Kobo interface manages two possible output formats: either a parsed JSON response as a list, or a crul::HttpResponse.

### CODE REVIEW

**Review by pr130 — APPROVED** [review]

**Comment by MKyhos** [comment]
LGTM! :100: :+1: Thank you so much :) 

As this PR has an earlier version of the `post-patch-methods` branch as an ancestor, I would suggest to proceed with
1. apply the new `styler` styling on to any branch to be merged (agreement necessary, see #46 )
2. merge `post-patch-methods` into `dev` (#32 )
3. merge `dev` into `issue29_manage_output_get`, selecting the newer post method versions on conflict
4. squash merge this branch on `dev`

**Comment by friep** [comment]
> LGTM! 💯 👍 Thank you so much :)
> 
> As this PR has an earlier version of the `post-patch-methods` branch as an ancestor, I would suggest to proceed with
> 
>     1. apply the new `styler` styling on to any branch to be merged (agreement necessary, see #46 )
> 
>     2. merge `post-patch-methods` into `dev` (#32 )
> 
>     3. merge `dev` into `issue29_manage_output_get`, selecting the newer post method versions on conflict
> 
>     4. squash merge this branch on `dev`

3.5. run the new styling command on this branch (i already spotted some pythonic styling :))

**Comment by pr130** [comment]
turns out #43 also includes the changes here... 🤯 
 https://github.com/CorrelAid/kbtbr/pull/43#issuecomment-866302960

**Comment by pr130** [comment]
lgtm :)

**Pull request merged**
