### PR TITLE
[#2] | Add pkgdown documentation

### PR DESCRIPTION
**Pull request by MKyhos**
**description from @friep** 

adds [pkgdown](https://pkgdown.r-lib.org/) documentation for branches `dev` and `main`. 

They will be available at:
- main: https://correlaid.github.io/kbtbr/main (https://correlaid.github.io/kbtbr/ will redirect to this)
- dev: https://correlaid.github.io/kbtbr/dev

a preview is available for the `pkgdown` branch: https://correlaid.github.io/kbtbr/pkgdown

how does it work?
1. Github action extracts the name of the branch and writes `_pkgdown.yml` so that `/tmp/docs/{branch_name}` is the destination folder for the build. Note that this is a temporary directory _outside_ of the repository. 
2. install package
3. build site to the temp directory from step 1. checkout the `_pkgdown.yml` to reset it to its empty state, then checkout the ` gh-pages` branch 
4. delete folder in `docs/{branch_name}` if it exists. move the temp directory to its place with `mv`. 
5. commit the updated `docs/{branch_name}` folder to the `gh-pages` branch.

one of the main challenges was that building the page would introduce changes in git - and then trying to checkout the gh-pages branch would result in git not being able to checkout the `gh-pages` branch with the following error: "Your local changes to the following files would be overwritten by checkout: ... Please commit your changes or stash them before you switch branches.". This is why we now build to a place outside git first, then checkout the `gh-pages` branch and copy in the new build. kind of dirty but it avoids having anything unstaged when checking out the branch.

### CODE REVIEW

**Comment by pr130** [comment]
@MKyhos was that intentional that the PR goes against `main`? :)

**Comment by MKyhos** [comment]
No it wasn't (edit but it would probably make no harm either. However, will close the pr later and reopen )

**Comment by pr130** [comment]
@MKyhos no worries, i just changed the base to `dev` (they added that a couple of months ago that you can change that.. phew). if we want to merge it to main, that's also fine with me, i just don't want to have all the cran checks running all the time (edit: for now)

**Comment by pr130** [comment]
i think it's working now? 👀 should we redirect `https://correlaid.github.io/kbtbr/` to `https://correlaid.github.io/kbtbr/main` ?

**Comment by MKyhos** [comment]
Very nice, very nice! :clap: :bow: Thank you so much!

RE redirection: either that, or we polish the current landing page accordingly such that it is nice to view and select the version of the documentation for the users :thinking:

**Pull request merged**
